### ISSUE TITLE
Bounty search is broken

### ISSUE THREAD

**Issue by 3rdwiki** [bountysource/core#1012]
The basic search function doesn't work.
Critical bug.

See [here.](http://bit.ly/ubuntubounties)

**Comment by sbts** [comment]
This is an ongoing issue, seems there are multiple bugs related to search not working over the last 2 years.
There has been no indication that any resolution has been proposed either.

This is very disappointing as it limits the discoverability of projects on a platform designed to help said projects

**Comment by arbylee** [comment]
This still seems to be an issue.  I see activity on the front page feed, but search only comes up with items as recent as 11 months ago

**Comment by rappo** [comment]
This is an issue we hope to resolve in the next few months, as time allows. The short explanation is that we need to change our search engine host for a variety of reasons (cost, compatibility, etc) and this issue will remain open until that happens.

**Comment by merarischroeder** [comment]
This is bizarre. This is a central feature and you have not fixed it in several months! I feel all tingly, I'm having an out of body experience. What bounty site DOESN'T fix their search facility within hours? If you're that desparate for help, I'll help you, I can't bear to watch. I'll have this working in 2 hours. Skype: alivate.hq

**Comment by ylavoie** [comment]
I completely aggree. There is no point in posting bounties if they can't be found. This should have been fixed immediately.

**Comment by merarischroeder** [comment]
Here is a very recent summary of all active bounties and the value of remaining money on them:

[https://docs.google.com/spreadsheets/d/161AkaokIYx80OyBdsAxm-xifuPGlDEubk7Ps5UBWCXA/edit?usp=sharing](https://docs.google.com/spreadsheets/d/161AkaokIYx80OyBdsAxm-xifuPGlDEubk7Ps5UBWCXA/edit?usp=sharing)

Of course, visit the links to get the most recent information.

From what I can see:

- there has been just over $190k of bounties created over the years, since Sep 2012.
- >$110k remains unclaimed

However:
- There is conflict in the bounty collection data
- from my data, more has been collected $363k, since Aug 2013. 
- only ~$20k more are claimed but not collected

This project is being held back, but poor maintenance. Imagine if this market-place grew 10x. It needs to reach critical mass, so all the best coders claim bounties and the backers flood in with their money.

**Comment by rappo** [comment]
@merarischroeder Appreciate the offer, but it's mostly a problem of time. I'll spare you the personal details but Bountysource is volunteer run and both founders (Warren and myself) have had many major (positive) life events happen all within the past few months. I use what little spare time I have now to process cashouts, fight fraud, handle major support issues, respond to tickets or irc, etc.

I would absolutely love if others could step in and offer support, like you've offered, but I fear the timing isn't right for us to make use of those contributions right now. You're free to make PRs or suggest changes, but know that you won't get any sort of technical assistance or feedback right away. And PRs will sit until we have time...

We plan to spend more Bountysource time after the holidays to address our major issues -- of which broken search is one. Please note that searching for a URL still works and will still forward you to the issue on Bountysource.

I can't give you accurate numbers right now but your number of "just over $190k" in bounties created is definitely very low. We've had over $300k in bounties just from one customer, IBM.

> This project is being held back [...] Imagine if this market-place grew 10x

We gave it a good run. Warren and I were full time on this project for *three* years, and for a while had a full time team of five others helping us with development and growth. It didn't work out we moved on, keeping this as a hobby / labor of love. 10x doesn't even come close to making it profitable. Current numbers just about cover service costs, nothing more. Similar developer marketplace sites like Upwork charge a 25-30% fee, but we get a lot of flak for even being 10% (and absorbing payment fees into that 10%) because we made the decision to provide a service for the open-source community. Bounties are also not the path to financial stability for Bountysource, Salt is. Monthly recurring revenue is a much better business model and doesn't leave us wondering if a surge of bounties will come in to cover costs every month.

If everyone wants to see Bountysource continue, two things are going to need to happen: 1) Please be patient and wait out the storm while we get our personal lives in order. 2) Step up with contributions (be it code, user support, or money) as soon as we're able to handle them. I want to see this become a thriving open-source project.

And if anyone out there at Amazon wants to give us some AWS credits, that'd be cool :).

**Comment by merarischroeder** [comment]
@rappo Thanks for the update! 

1. This sort of thing would work well on a BountySource blog.

2. I recommend Patreon for BountySource, although I suspect that's what Salt is for. Maybe both? You're currently like Wikipedia, and you need to ask visitors for direct support. After you have easy places to send you money, approach larger firms like Linux Foundation and more, and ask for some monthly income.

3. BountySource v2 - It would make a lot of sense, if GitHub bought your brand and handled bounties on their platform directly.

4. There are not enough developers on Earth. You need to concentrate on your best target market - University Students. They can learn and earn.

5. Bite sized chunks. You need to encourage bounty rewarders to make smaller scopes with lower cost. When I look through bounties, I'm thinking, too hard, too big, too hard.. Smaller bounties could help.

6. 3 years full time is a lot. I'm involved deep within Startup Culture in Australia, and I'm a coder. It would have been great if you finished it in 3-6 months, and had no CVS integration. Then only improved it after positive cashflow. You probably agree in hindsight, another life lesson.

7. Ruby - I only have limited time, hence posting my own bounty prize, for one of my open-source projects. I do want to see this bounty industry thrive. I must admit, I was put off by Ruby. Ruby developers are among the highest paid developers (because there are so few of them). If you built BountySource with PHP or Node.js, you would have a lot more potential contributors. Perhaps another life lesson learned.

**Comment by rappo** [comment]
@merarischroeder, thanks for the feedback.

1. It would be, I just don't have the energy or desire to maintain a blog :)
2. People are already contributing on Salt, https://salt.bountysource.com/teams/bountysource. We've also added a donation prompt on checkout.
3. v2... we're on like v6 at this point! We've been around since 2004 :). I think a purchase by anyone is unlikely, but we'd welcome interested parties if Bountysource could continue our mission with additional support.
4. Our primary targets are either 1) freelance / oss developers who want to create their own schedule to build products or 2) full time developers who already contribute to OSS, but would love a little kick-back or help prioritizing features
5. I know search is broken so it's hard to verify this, but bounties range from $5 to $5000, for small medium and large tasks. It's not up to us. We provide the platform and let backers and developers determine the effort and cost.
6. I don't agree, but I definitely would have changed a few things. For starters, I would have focused on recurring revenue as early as possible.
7. Ruby was and remains the right call for the task at hand, and especially for the team that built it (Warren is one of the best Ruby devs in the world, in my opinion). PHP is 'old' and Node is too new and full of its own problems and high cost of developers.

**Comment by Cervator** [comment]
Appreciate the extra details @rappo, that helps a lot vs the mostly quiet times on IRC just seeing error reports roll by.

I just bumped myself up to the second tier for you on Salt, but yeah that probably doesn't even cover half an hour of dev time a month. I would love to witness the promised land after the holidays, but as a project lead for a sizable open source project myself ... I am familiar with wishful thinking :-)

Unless you're hiding an ace or two up your sleeve somehow I'm not seeing much hope for a sudden reversal of fortunes even after the holidays (beyond a few critical fixes). I'm surprised and impressed to learn how long you've been at it, but also wonder if that isn't an indicator for attempting a different approach. Is there anything serious/legal keeping you from attempting to find a few more core contributors to not just submit PRs but help review, merge, and release them?

That would seem less scary than inviting in contributors to help with the sys admin stuff, and you can put gates on the release process for added comfort. Although I suspect a fair amount of us do have spare hardware capacity floating around in the clouds. I don't know how much power you need but clever setups can be added to help spread the load (although the initial setup would be limited as usual - time time time)

Incidentally I'm not trying to volunteer myself. As much as my library-itis makes me love adopting more projects my main contributors would lasso me in and chain me to our CI server till I come to my senses :-) But I wish we could do more for Bountysource, it is a worthwhile project and maybe it could take the community angle to the next level if it simply isn't likely to pull a profit any time soon if ever. In the meantime I'm reluctant to add any more bounties considering the site's and maybe the service's stability and longevity.

**Comment by rappo** [comment]
@Cervator 

> I just bumped myself up to the second tier for you on Salt

Thank you, it really means a lot! Any amount is appreciated. 😍 

> Is there anything serious/legal keeping you from attempting to find a few more core contributors to not just submit PRs but help review, merge, and release them?

Nothing legal/serious stopping us, it's purely logistics and planning time we don't have at the moment. The code is far too undocumented and there are no clear standards/etc publicly established, so the burden on us for helping (eg getting a dev environment up and running, reviewing PRs, etc) is far too high at this point.

We're in favor of adding core trusted developers, but without any time to get that set up properly that means some magical kick-ass developer needs to show up, doesn't need any coaching, and is making great contributions with almost zero assistance. That seems unlikely, so we're not going to push on that until it makes sense to us.

**Comment by jcrben** [comment]
I tossed a $15 bounty on it: https://www.bountysource.com/issues/32111038-bounty-search-is-broken

I don't even use the search, but I'd like to see this project in good shape. If people want this and, like me, don't have time to fix it, add to the bounty...

**Comment by frnco** [comment]
@rappo any plans on what will replace Sphinx?

I am considering simple DB queries for indexable fields, but for fulltext searches it should use something like elastic search, Lucene etc.

If it's not feasible to decide and implement a solution quickly I plan on making it possible to at least searching for indexable fields, then later we can figure out the best way to do full text, do you think it's acceptable?


Any insights on why Sphinx is being ruled out and limitations on choosing alternatives will be very helpful, I really wanna get this search working but design decisions must make you happy, it's your baby after all.

**Comment by frnco** [comment]
@rappo Search is working again, don't know if you guys changed something on the server or what fixed it but this can be closed now.

**Comment by jcrben** [comment]
@rappo I'm OK with your internal team collecting the bounty I started, if you'd like to make a claim. If not, close it out and I'll donate the $15 I put up.

**Comment by rappo** [comment]
We didn't do anything to fix this... it just happened magically. Strange. I'll close and refund, if you want to donate to re-purpose the bounty money, great!
