### ISSUE TITLE
There are no issues for the Linux kernel.

### ISSUE THREAD

**Issue by 3rdwiki** [bountysource/core#1109]
Okay - so I just typed in Linux kernel into the search box,
and it says that there are no issues ?

Look for yourself: ( 0 issues )

https://www.bountysource.com/teams/linux/issues

Archive for when it's fixed : https://archive.fo/6D8BK

**Comment by rappo** [comment]
not a bug, by design all teams are tied to github orgs / projects as highest priority. https://github.com/torvalds/linux has no issues.

Linux kernel issues can be found here: https://bugzilla.kernel.org/

Since bugzilla isn't centralized and we don't connect to any API for it, issues need to be manually searched for by the specific bugzilla issue url.
