### ISSUE TITLE
Bounty not updating on issue

### ISSUE THREAD

**Issue by gingerbeardman** [bountysource/core#1124]
https://github.com/libretro/RetroArch/issues/3671

bounty was left by me on Jul 7, 2017 4:31:08 PM

**Comment by Cervator** [comment]
Hey there. Good news is that the bounty *did* stick, as you can see at https://www.bountysource.com/issues/37999364-input-remapping-limitations

But the GitHub integration has been problematic for a while now. More details over at #1096 - might it be that whomever originally set up the Bountysource integration for that repo has since revoked their OAuth tokens? Even if the integration is re-enabled after that it seems unable to update issues again.

**Comment by gingerbeardman** [comment]
In that case, with the increased bounty not being visible in github I'd like to withdraw it. I'm sure you understand. Thanks

**Comment by Cervator** [comment]
Sure - done :-)

Your comment there did indicate the extra available funds, and you might be able to reach a project maintainer who can edit it into the top post for more visibility. In any case unless you want to put it back now you might want to edit your comment to note that the extra funds were retracted

I'll close this then since #1096 covers the troubled integration. Will probably put a bounty on that to see if somebody will step in and help fix it.
