### ISSUE TITLE
Creating a Seed DB

### ISSUE THREAD

**Issue by vigasdeep** [bountysource/core#1131]
I would like to create a Seed DB, will need some guidance. Other than a user, what should be in seed DB? @rappo  @Cervator

**Comment by Denu8thell** [comment]
I would add some trackers (for repos, maybe some ones other than github if you can make that work) as well, I would just have them point to some of the bigger projects (one pointing to this repo would be cool), or maybe we just want some test repos set up, then you can just have some issues closed that are paid out, some that are in progress. That's a lot more work, but would be kinda cool.

Also some teams would be good. 

Those are the main things I think.

**Comment by vigasdeep** [comment]
I didn't think about this, I'd like to get my hands dirty in code, so yeah, cool! What should I do with this to start working?

**Comment by Denu8thell** [comment]
http://www.xyzpub.com/en/ruby-on-rails/3.2/seed_rb.html
Something like this ^

You can either try to write them from scratch, or try to set up how you think the seed database should look, and export the data like the bottom section in that link. The second option might be easier.

Testing would be running `docker-compose -f docker-compose.yml -f tasks.yml run seed` and seeing if that seeds the database correctly.

I don't know how much you know about ruby on rails, but if you don't know much, take a look in the app/models for the models and related schema information.

**Comment by vigasdeep** [comment]
Okay, so we just need commands which we execute inside 'rails c', and put them in the seed.db file.

What should be there? Here's what I could think of (please add/modify accordingly)
1. Few demo users, with some balance in their account (like they have in PayPal sandbox accounts)
2. A demo team
3. Some GitHub projects? real ones or fake?

What else?

What did you mean when you said 'I would add some trackers', unable to understand, what do you mean by trackers here?

**Comment by Denu8thell** [comment]
When I say "trackers", I'm referring to tracking Github projects. They're called trackers because they "track" the repository. See app/models/tracker.rb for more information on that.

I don't know if the repositories should be fake or real, I think either way is fine, but they each have their own advantages/disadvantages.

A real repo is easy to just track, you don't have to set it up or anything, but things can change in them; Issues can open and close, they aren't static like a dev site probably should be.

Setting up a fake repo might be a little more work, but you can set up some closed and paid out issues, and have it stay the way it is forever.

My personal opinion is to set up fake repos. Other opinions on it would be nice.

That's all I can think of right now as far as what needs to be in the seed database.

**Comment by vigasdeep** [comment]
Okay, I'll get started on this issue. Cheers.

**Comment by NoNonsense126** [comment]
#1221
