### ISSUE TITLE
Signin / Signup Internal Server Error

### ISSUE THREAD

**Issue by lumodon** [bountysource/core#1145]
Bug report for deployed version (live website at https://www.bountysource.com/signin)

1. When signing up first with github OAuth I get an error flash message: "Internal Server Error"
1. Next I try to sign up using email and creating new account, same problem "Internal Server Error"
1. Lastly I realized I'm using adblock so I disabled my adblock, deleted my cookies (Chrome browser application tab) and tried again - no luck same exact error, adblock was not the problem.

here's frontend console log output:
```
jsapi:22 A Parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/?file=visualization&v=1.0&packages=corechart, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi:22
2jsapi:22 A Parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/api/visualization/1.0/40ff64b1d9d6b3213524485974f36cc0/format+en,default+en,ui+en,corechart+en.I.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi:22
2api.bountysource.com/decide/?verbose=1&version=1&lib=web&token=f9b55dbcc390114a4ed685391a7563e0&ip=1&_=1507668928244 Failed to load resource: the server responded with a status of 404 (Not Found)
signin:1 Failed to load https://api.bountysource.com/decide/?verbose=1&version=1&lib=web&token=f9b55dbcc390114a4ed685391a7563e0&ip=1&_=1507668928244: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://www.bountysource.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
api.bountysource.com/cart?autocreate=false Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js:9778 API Error
(anonymous) @ angular.js:9778
angular.js:9778  * Request POST https://api.bountysource.com/user
angular.js:9778  * Request Params Object
angular.js:9778  * Response: Object
```

**Comment by pva** [comment]
Same here!

**Comment by Denu8thell** [comment]
Alright, so just going to add some information here.

Apparently, Bountysource has been [suspended](https://developer.github.com/apps/building-integrations/managing-oauth-apps/troubleshooting-authorization-request-errors/#application-suspended) for whatever reason. 

This may simply be a symptom of some other problem, because GitHub will suspend an app if it thinks it's spamming, or abusing the API in some way. You can see in the URL that there is an error message that GitHub is passing to Bountysource, but it Bountysource doesn't seem to handle the error gracefully, like actually displaying the error on the screen.

So, anything related to the GitHub API isn't working, I assume. Including updating GitHub issues. I'm thinking that this is some larger issue though, since there have been several errors related to the GitHub API recently, and it might just be a coincidence that it coincided with the server switch, I dunno. 

This is a problem that someone who has access to the OAuth access tokens needs to fix, like @rappo or @wkonkel, not sure who has access to what.

**Comment by sc0w** [comment]
I can login into https://www.transifex.com/ using the github account, so, the problem is in bountysource

I writed to support@github.com and they answer me:

> **In order for us to help troubleshoot any application errors, we'd need to hear from the owners of the application.**

and, I writed to support@bountysource.com and I recieved no answer

please, bountysource developers, can you contact to support@github.com to fix this issue?

thanks a lot

**Comment by Cervator** [comment]
I'm unsure if the recent server move might have (temporarily?) caused a different signup problem, I do see some commit traffic for fixes that might relate.

There is definitely a GitHub API issue we need to resolve, I'll suggest we use #1147 for that, and when it is fixed recheck this one to make sure any other user registration issues are gone as well

**Comment by rappo** [comment]
Closed per https://github.com/bountysource/core/issues/1147#issuecomment-347921924
