### ISSUE TITLE
Is this a rip-off?

### ISSUE THREAD

**Issue by Symbolics** [bountysource/core#1169]
Tried to cash out.
Balance went to $0 on 14th of December
Now 6th of Jan, no payment received
No answers from support
No answers from previous issues raised here

Be careful folks...

**Comment by Cervator** [comment]
Hi @Symbolics - there is some reorganization on-going at the moment so I haven't personally checked the support queue for a while (also happen to be on a different continent for now). So long as you did email support@bountysource.com it'll get handled, just please be patient :-)

**Comment by Symbolics** [comment]
Any ideas on this? It has been 30 days now since the bounty funds went to $0, but still no refund.

**Comment by rappo** [comment]
@Symbolics, I do not see any pending cashouts from you or your team. Cash outs are requested by https://www.bountysource.com/activity/cash_outs/new. Cash outs do not happen automatically because many users choose to use their funds for bounties/etc. You must request a cash out and provide details so we know where and how to send the funds. As soon as you do that we can process your cashout.

**Comment by Symbolics** [comment]
David, that is the problem. I request a cash-out on the 19th of December, it was 'processed' and my balance went to $0, but my Pay-Pal account was never credited and the refund never received.

**Comment by daveloyall** [comment]
@Symbolics, is this an open issue?

**Comment by Symbolics** [comment]
No, refund received, thanks.

--
Steve Nunez
Senior Director, Field Technical Services, APAC
+65 9623 5172

[MapR_technologies_logo_signature_transparent]

**Comment by digitalshakra** [comment]
Hi Symbolics,

Can you email me at support@bountysource.com with some your bountysource/paypal email details?
Let's get this resolved!

Johan
Bountysource Support

**Comment by Symbolics** [comment]
Thank you for the follow-up. Resolved already.
