### ISSUE TITLE
Fix Synchronization Issues between Github and Bountysource

### ISSUE THREAD

**Issue by volas** [bountysource/core#1401]
support@ ignores my email, so now I'm here!

We have one issue that was closed long time ago on Github, but still open on Bountysource:
https://www.bountysource.com/issues/60516752-proposal
``https://github.com/TauCetiStation/TauCetiClassic/issues/2594``

And I can do nothing about it. The worst part - it's very rude and emotional message, and I can't even edit the text.

**Comment by volas** [comment]
And now this is top backed issue on our bountysource page :sweat_smile:

**Comment by johanlives** [comment]
A bounty has been posted on this issue.

We need to know why the sync isn't working in this instance.    Intermittent syncing issues have occurred in the past but normally resolve given time. 

Can you find the reason for this persistent syncing issue?

**Comment by johanlives** [comment]
Bounty increased by $50

**Comment by alphashuro** [comment]
Hi @johanlives, the issue was that the production db had a character limit of 255 chars on the `labels` column for the issues table, and thus the indicated issue was not being saved during syncing. I've fixed this by changing it to a much larger number, and the change worked on my local machine so I changed the prod db as well and we should see the issue synced successfully on Bountysource as well once the sync job runs. I will check periodically and let you know once it has synced and closed the issue :)

**Comment by volas** [comment]
@johanlives @alphashuro issue now closed on bountysource too, thanks!

**Comment by johanlives** [comment]
Thanks Alpha, seems to have done the trick
