### ISSUE TITLE
Protection of donation funds in the event of bankruptcy

### ISSUE THREAD

**Issue by timabell** [bountysource/core#955]
Hi, this isn't a technical issue but this seems like a good place to raise it publicly for discussion.

I noticed when I made a donation that you said that all money paid in belongs to Bountysource, and that you are explicitly not an escrow service (_"All amounts paid to Bountysource under this Agreement belong solely to Bountysource"_ ~ [terms of service](https://www.bountysource.com/terms)) . Given that you only pay out the money when a feature is completed this leaves you sat on a potentially large pile of cash that you could be liable to pay out (less your 10% fee).

**What if any protections do you have for this cash to prevent it being taken by creditors in the event that your company fails?**

Or even if you decided to close the company voluntarily, sell it, or change the mission. I would have an expectation that any money donated would be refunded, or paid out, and as your terms currently stand this looks highly unlikely.

I wish you all the best and hope this never needs to be tested, but think people need to be persuaded that their money is safe in your hands while they wait for development of their desired features to progress.

This threat to the funds is not an imagined one, and there is precedent for such a collapse with the Farepak christmas savings club, which you can read more about here: http://www.theguardian.com/business/2012/jun/21/farepak-hbos-collect-cash-bust

---

I hope you succeed in changing the funding of open source for the better forever, bringing much needed balance against the current plague of software that is funded and directed _against_ the interests of the end users.
##

**Comment by ssbarnea** [comment]
Quite an interesting subject. I am new to this platform and I observed two related issues: got my first supported that told me he could not use the platform because it would not allow him to put a time limit on small amounts, he was willing to pay $20 for something but obviously we would want to pay only if this happens in some time, not as in maybe never. Now I have to investigate new options.

Second problem is that if BountySource would be non-profit people would be able to use corporate support to double the amount of their donations. Still this does not apply in this case but seems to be a big flaw in the business model.

**Comment by rappo** [comment]
Hi! This is an interesting topic and I'm glad it was out in the open for people to discuss. I'm pruning issues so that only bugs or product improvements are in the backlog (and removing stale/dead tasks). Closing this out.

**Comment by timabell** [comment]
It's a shame github doesn't provide a better way of discussing such issues. A Discourse integration would be nice.

If you plan to address this concern elsewhere then please do point me to it. I'd like to hear your official response.
